---
- name: Import docker apt key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add docker apt repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'

- name: Update package list
  apt: update_cache=yes

- name: Install docker package
  apt: name=docker-engine state=present

- name: Add docker group
  group: name=docker state=present

- name: Add docker group to vagrant user
  user: name=vagrant groups=docker append=yes

- name: Start docker service
  service: name=docker state=started enabled=true
